dymensionxyz/rollapp-evm

- .github/workflows/e2e-tests.yml
Close: [#29](https://github.com/dymensionxyz/e2e-tests/issues/29)
> CI: Add workflow for trigger E2E tests

- .github/pull_request_template.md
- .github/workflows/codeql.yml
- .github/workflows/golangci_lint.yml
- .github/workflows/markdown_lint.yml
- .markdownlint.yaml
- README.md
- app/ante.go
> ci: update workflows and template

- Makefile
- docs/swagger-ui/swagger.yaml
- go.mod
- proto/buf.gen.swagger.yml
- proto/swagger_config.json
- scripts/protoc-swagger-gen.sh
Closes #128 
I have...
SDK Checklist
----;
For Reviewer:
---;
> Feat: add swagger config and make scripts

- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> Update dymension rdk to use ibc-denom trace

- scripts/settlement/add_genesis_accounts.sh
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(test scripts): make alice and bob keys in .rollap dir

- scripts/templates/example-dym-denommetadata.json
…el-0
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> chore(utils): added template for registering dym metadata to rollapp 

- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> build(deps): updated dymint to eb08e30da2c

- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> build(deps): updated rdk to v1.5.0-beta

- README.md
- scripts/update_genesis_file.sh
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> chore(local setup): update the  script to new hub-genesis param name

- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> build(deps): updated evmos fork to `v12.1.6-dymension-v0.4.0`

- scripts/init.sh
- scripts/update_genesis_file.sh
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix: updated block size and evm market fee

- README.md
- scripts/ibc/setup_ibc.sh
- scripts/init.sh
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(scripts): add an option to skip evm base fees

- app/app.go
…fig.
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(app): fixed bech32 on account keeper to not be hardcoded 

- scripts/update_genesis_file.sh
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(scripts): fix hubgenesis tokens in update genesis

- .github/workflows/changelog.yml
- CHANGELOG.md
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> feat(ci): Add changelog log auto update workflow

- CHANGELOG.md
- README.md
- scripts/update_genesis_file.sh
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(local script): updated default genesis created on extended guide with EIP 3855

- .github/workflows/e2e-tests.yml
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> Revert to use main branch on e2e-tests

- CHANGELOG.md
- scripts/ibc/setup_ibc.sh
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(init scripts): update account-prefix in ibc script

- CHANGELOG.md
- scripts/update_genesis_file.sh
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix: remove deprecated denommetadata param

- app/app.go
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(app): Changed to use sequencerKeeper instead of stakingKeepr in ibcKeeper

- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> build(deps): bump dymint to v1.1.0-rc02 and rdk to v1.6.0-rc02 and downgraded cosmosclient to v0.4.2-beta

- README.md
- go.mod
- go.sum
- scripts/update_genesis_file.sh
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(local script): updated with latest relayer version and extra eips

- Dockerfile
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> chore!: Bump base image to golang:1.22.2-alpine3.18

- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(deps): update evmos tag v0.4.1 to block vesting account

- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(deps): updated dymint to v1.1.0-rc03 to solve gossip bug

- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(deps): updated protobuf to v1.33.0 due to vulnerability

- CHANGELOG.md
- scripts/init.sh
- Currently, we have the wrong logic here https://github.com/dymensionxyz/rollapp-evm/blob/8050f59de96fde9130b00738048462860ce51be8/scripts/init.sh#L116
this will make us fail when try to add `governer` to genesis when run `init.sh`
it should be `if [ ! "$answer" != "${answer#[Nn]}" ] ;then`
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> chore: Fixed wrong logic in `init.sh`

- README.md
- scripts/init.sh
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(readme): fix governor creation and block time substition missing in readme

- CHANGELOG.md
- Dockerfile
- README.md
- go.mod
- go.sum
- scripts/ibc/rollapp.json
- scripts/ibc/setup_ibc.sh
- scripts/init.sh
- scripts/update_genesis_file.sh
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(readme): fix bech32 readme scripts

- .github/workflows/codeql.yml
- CHANGELOG.md
- Dockerfile
- Makefile
- README.md
- app/app.go
- go.mod
- go.sum
- scripts/ibc/rollapp.json
- scripts/ibc/setup_ibc.sh
- scripts/init.sh
- scripts/update_genesis_file.sh
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> feat: set bech32 prefix without changing source code

- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(deps): bump dymint to v1.1.0-rc04 to fix account error not causing panic

- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(deps): bumped dymint to v1.1.0-rc05 to fix da sync issue

- Makefile
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(build): Added ledger and netgo support in makefile when make install

- go.mod
- go.sum
…ntehandler
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(deps): bump evmos to v0.4.2 to fix vesting msgs not blocked in eip712 ante handler

- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> build(deps): updated dymint and rdk to official releases of 1.1.0 and 1.6.0 respectively.

- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(deps): bumped dymint to v1.1.1 to fix da health event fast emmision

- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(deps): bump dymint to v1.1.2 to fix full node sync issues

- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(deps): bump dymint to v1.1.3-rc01 to fix full node p2p initial sync issues

- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(deps): bump dymint to `v1.1.3-rc02` to fix unsync issue when da is down

- .github/workflows/e2e-tests.yml
----
Closes #234 
I have...
SDK Checklist
----;
For Reviewer:
---;
> Trigger e2e-tests for Rollapp-EVM

- scripts/init.sh
----
Closes #231 
I have...
SDK Checklist
----;
For Reviewer:
---;
> chore(local test): Change default max block size to 500k

- scripts/init.sh
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(readme): fixed init script with broken consensus params

- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(deps): updated dymint to hotfix v1.1.1-hotfix.3

- app/app.go
- app/upgrades/v2.2.0/upgrade.go
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> refactor(upgrade handler): moved upgrade handler to it's own package 

- .github/workflows/changelog.yml
- .markdownlintignore
- CHANGELOG.md
- app/app.go
- app/upgrades/v2.2.0/upgrade.go
- scripts/init.sh
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> chore(rebase): rebase changes from main 

- .github/workflows/e2e_test_upgrade.yml
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> ci: add workflow for trigger upgrade hub e2e-test

- .githook/pre-push
- README.md
- scripts/setup-git-hooks.sh
This PR add pre push hooks and instruction on README
- Golangci-lint
- Markdownlint
I have...
SDK Checklist
----;
For Reviewer:
---;
> Feat: Add setup script and git push hooks

- scripts/ibc/rollapp.json
- scripts/ibc/setup_ibc.sh
- scripts/init.sh
> chores: change min_gas_price to 10000000.0

- go.mod
- go.sum
----
This change introduces breaking changes to dymint and default configuration should be adjusted accordingly.
more of the changes can be found here: https://www.notion.so/dymension/Dymint-v1-1-3-migration-Guide-13fe5964bec546228290d5b70bb9a65c?pvs=4 
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> chore(deps): bump dymint to `v1.1.3-rc04` and rdk to `v1.6.1-rc01`

- go.mod
- go.sum
----
This PR bumps deps to fix missing parser for `x/erc20` messages
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> chores(deps): bumps evm be rpc to `v1.1.4` and be rpc to `v1.2.4`

- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> build(deps): bumped dymint to v1.1.3-hotfix.1

- .github/workflows/build_and_push_images.yml
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(github): use go 1.22.4 or greater in action

- app/app.go
see also
- https://github.com/dymensionxyz/dymension-rdk/pull/476
- https://github.com/dymensionxyz/rollapp-wasm/pull/97
> fix(code standards): cleans up blocked addresses in app.go

- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> feat(debug): use dymint-v1.1.3-hotfix.2 which has profiling

- README.md
- scripts/init.sh
…lement
docs: add the lacking values to the README
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(scripts): update init script to support mock and real da and settlement

- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> build(deps): bumped dymint to `v1.2.0-rc01`

- README.md
- scripts/ibc/setup_ibc.sh
- scripts/settlement/register_rollapp_to_hub.sh
- scripts/settlement/register_sequencer_to_hub.sh
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> chore(scripts): change broadcast-mode to sync

- app/app.go
- cmd/rollappd/cmd/root.go
- go.mod
- go.sum
chore: set sensible defaults pruning
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> chore: disable pruning by default

- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> build(deps): bumped dymint to `v1.2.0-rc03`

- scripts/settlement/register_sequencer_to_hub.sh
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> chore: add dummy seq metadata

- README.md
- go.mod
- scripts/init.sh
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> updated readme and dependecies

- app/app.go
- app/evm_sequencers_keeper.go
- app/evm_sequencers_keeper_test.go
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(sequencers): get by cons addr in all scenarios on EVM

- scripts/settlement/register_sequencer_to_hub.sh
related to https://github.com/dymensionxyz/dymension/pull/1111
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> chore: update register script to support positional argument change

- scripts/ibc/setup_ibc.sh
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> chore: add gas flags to funding command

- scripts/ibc/setup_ibc.sh
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> chore: update ibc setup script rc

- scripts/minimal_update_genesis_params.sh
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> chore: update min genesis script with unbonding params

- README.md
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> chore(scripts): bump relayer version in readme

- Makefile
- go.mod
- go.sum
- scripts/init.sh
----
Closes #329 
I have...
SDK Checklist
----;
For Reviewer:
---;
> chore(scripts) init da in init.sh script instead of using ldflags

- scripts/init.sh
----
Closes #332
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(scripts): init script fix da rollapp param for celestia mocha

- README.md
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> chore(docs): bump relayer version in readme

- app/ante/bypass_ibc_fee_decorator.go
- app/ante/create_account_decorator.go
- app/ante/handlers.go
- app/ante/sigcheck_decorator.go
- go.mod
- scripts/ibc/setup_ibc.sh
- scripts/init.sh
- scripts/settlement/register_rollapp_to_hub.sh
----
Closes #335 
I have...
SDK Checklist
----;
For Reviewer:
---;
> feat(ante): Create new account if not exists and skip fees for relayer IBC messages

- .github/workflows/release_binary.yml
- .goreleaser.yml
- Makefile
CI was tested on a forked repository and on amd64/arm64 ubuntu linux boxes using `release-dry-run` command. 
This CI is necessary for a smoother process of the roller mock flow. Since we'll have pre-built binaries, we won't have to build it during the dependency installation
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> ci: add ci for creating mock binaries on release

- app/ante/bypass_ibc_fee_decorator.go
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(ibc decorator): fixed bad comparison for ibc messages.

- go.mod
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(deps): bumped dymint to `d51b961e7` to fix stuck submission bug

- .goreleaser.yml
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> ci: fix the bech32 prefix for mock binaries

- app/ante/create_account_decorator.go
- app/ante/sigcheck_decorator.go
- go.mod
- go.sum
----
Closes #345 
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(deps): dymint bump to include da grpc fix

- app/app.go
- go.mod
- go.sum
- scripts/init.sh
- scripts/settlement/register_rollapp_to_hub.sh
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> feat(genesis_bridge): revised genesis bridge

- .github/workflows/e2e-tests.yml
- .github/workflows/e2e_test_upgrade.yml
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> chore(CI): trigger workflow manually

- scripts/minimal_update_genesis_params.sh
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> chore: update minimal genesis script to remove accounts

- app/app_test.go
- app/test_helpers.go
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix failing tests

- scripts/ibc/setup_ibc.sh
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(scripts): adjusted IBC script to work with whitelisted relayers

- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(version): bump dymint and rdk to latest

- go.mod
- go.sum
…e of evm hook usage.
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(deps): double events on evm transfer

- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(version): bump dymint to c0e39f93d729

- app/ante/ante.go
- app/app.go
- go.mod
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix: feegrant ante handler wiring

- go.mod
- go.sum
----
Closes #387 
I have...
SDK Checklist
----;
For Reviewer:
---;
> feat(deps): command to validate genesis/bridge

- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> dep(erc20): updated dep to include erc20 register tx

- app/app.go
----
Closes #392 
I have...
SDK Checklist
----;
For Reviewer:
---;
> feat(upgrade): move drs check to begin blocker to allow time-based upgrades

- app/app.go
- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> feat(deps): new genesis-bridge flow and rollappparams upgrade fix

- README.md
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> docs: bump relayer version

- genesis-templates/DRS/1/genesis-mainnet.json
- genesis-templates/DRS/1/genesis-testnet.json
- genesis-templates/DRS/2/genesis-mainnet.json
- genesis-templates/DRS/2/genesis-testnet.json
- scripts/generate-genesis-template.sh
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(genesis-templates): fixed genesis template generator and drs 1,2 templates

- go.mod
- scripts/init.sh
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> feat(script): added replacement for gas_denom

- app/upgrades/drs-2/upgrade.go
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(drs): drs-2 migration default gas denom fix

- cmd/rollappd/cmd/root.go
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> feat(build): add ability to override bech32 with env var 

- Dockerfile
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> chore: Add devd tool to image for erc20 tests

- Makefile
- app/app.go
- app/upgrades/drs-2/upgrade.go
- app/upgrades/drs-3/constants.go
- app/upgrades/drs-3/upgrade.go
----
Closes #408 
I have...
SDK Checklist
----;
For Reviewer:
---;
> feat: add DRS3 upgrade handler

- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(deps): bumped evmos to fix foreign gas denom rpc call

- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> feat(deps): bumped rdk to support tokenless feature

- genesis-templates/DRS/3/genesis-mainnet.json
- genesis-templates/DRS/3/genesis-testnet.json
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> feat(genesis-templates): add genesis templates for drs 3

- app/ante/ante.go
- app/ante/handlers.go
- app/app.go
- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> feat: wired signless execution

- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> chore(deps): updated evmos dep to rc tag

- app/app.go
- app/upgrades/drs-4/constants.go
- app/upgrades/drs-4/upgrade.go
----
Closes #419 
I have...
SDK Checklist
----;
For Reviewer:
---;
> feat(upgrade): add upgrade handler for DRS4

- app/app.go
- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(rollappparams): Validate gas price gov proposal param change

- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> chore(deps): Updated rdk to v1.8.0-rc01 tag

- Makefile
- genesis-templates/DRS/4/genesis-mainnet.json
- genesis-templates/DRS/4/genesis-testnet.json
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> feat(drs): updated makefile and templates to DRS 4

- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> feat(deps): updated dymint to v1.3.0-rc02 to support skip validation height flag

- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(deps): bumped dymint to v1.3.0-rc03 to fix multiple forks sync issue

- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(deps): bumped rdk to v1.8.0-rc02 to include 2 minor fixes to tokenfactory and timeupgrade

- go.mod
- go.sum
…tration bug.
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(deps): bumped evmos to fix token-pair registration bug

- Makefile
- genesis-templates/DRS/5/genesis-mainnet.json
- genesis-templates/DRS/5/genesis-testnet.json
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> feat(drs): Added genesis templates for drs 5

- README.md
- app/app.go
- app/upgrades/drs-2/upgrade.go
- app/upgrades/drs-5/constants.go
- app/upgrades/drs-5/upgrade.go
- scripts/settlement/register_sequencer_to_hub.sh
----
Closes #428 
I have...
SDK Checklist
----;
For Reviewer:
---;
> Upgrade DRS version to 5

- genesis-templates/DRS/5/genesis-mainnet.json
- genesis-templates/DRS/5/genesis-testnet.json
- scripts/generate-genesis-template.sh
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> feat(genesis-template): changed default delegator unbonding time in genesis template

- genesis-templates/DRS/5/genesis-mainnet.json
- genesis-templates/DRS/5/genesis-testnet.json
- scripts/generate-genesis-template.sh
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> feat(genesis-template): changed delegator default min commision rate to be 0

- scripts/init.sh
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> feat: allow grpc CELESTIA_NETWORK when running setup script

- .github/workflows/build_image_with_dymint.yml
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> chore(ci): fix build image command

- .github/workflows/build_image_with_dymint.yml
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> chore(ci): checkout to rollapp-evm repo before build image

- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> feat: use rdk v1.8.0-rc02-3d-migration dymint v1.3.0-rc03-3d-migration

- app/app.go
- app/upgrades/drs-2/upgrade.go
- app/upgrades/drs-3/upgrade.go
- app/upgrades/drs-4/upgrade.go
- app/upgrades/drs-5-from2d/constants.go
- app/upgrades/drs-5-from2d/doc.go
- app/upgrades/drs-5-from2d/upgrade.go
- app/upgrades/drs-5-from2d/upgrade_test.go
- app/upgrades/drs-5/upgrade.go
- app/upgrades/types.go
- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> feat: use rdk v1.8.0-rc02-3d-migration dymint v1.3.0-rc03-3d-migration (fixed)

- .github/workflows/build.yml
- .github/workflows/build_image_with_dymint.yml
- .github/workflows/e2e-tests.yml
- .github/workflows/e2e_test_upgrade.yml
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> chore(ci): bump actions/upload-artifact to v4

- cmd/rollappd/cmd/root.go
- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> deps(rdk): updated rdk dymint deps

- app/app.go
- app/upgrades/drs-5-from2d/upgrade.go
- app/upgrades/drs-5-from2d/upgrade_test.go
- app/upgrades/types.go
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(migration): add missing evmos params from 2D

- app/app.go
- app/upgrades/drs-5-from2d/upgrade.go
- app/upgrades/drs-5-from2d/upgrade_test.go
- app/upgrades/types.go
- cmd/rollappd/cmd/root.go
- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> feat: bump dymint + rdk + 3d migration fixes

- app/app.go
- app/upgrades/drs-6/constants.go
- app/upgrades/drs-6/doc.go
- app/upgrades/drs-6/upgrade.go
- app/upgrades/drs-6/upgrade_test.go
- app/upgrades/types.go
- upgrade to version DRS 6 
- fix vesting accounts that have start and end times out of bounds due to having them expressed in milliseconds
----
Closes #457 
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(upgrade): correct vesting accounts start and end time

- app/ante/ante.go
- app/app.go
- cmd/rollappd/cmd/root.go
- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(deps): now ibc genesis tx is free

- cmd/rollappd/cmd/root.go
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix: remove pruning cmd added by mistake

- app/ante/ante.go
- app/app.go
- cmd/rollappd/cmd/root.go
- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(ibc): bump rdk + missing keeper to fix failed gensis tx

- scripts/ibc/setup_ibc.sh
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(scripts): support relay to v50

- scripts/ibc/setup_ibc.sh
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(scripts): whitelist relayer in ibc

- Makefile
- genesis-templates/DRS/7/genesis-testnet.json
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> feat(drs): new drs 7 with template

- Dockerfile
- app/app.go
- go.mod
- go.sum
- scripts/init.sh
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(erc20): fix staking erc20 token
